// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	List(ctx context.Context, arg ListParams) ([]ListRow, error)
}

var _ Querier = (*Queries)(nil)
